package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"fmt"
	"learn-gqlgen/graph/model"
)

// Depressions is the resolver for the depressions field.
func (r *queryResolver) Depressions(ctx context.Context) ([]*model.Depression, error) {
	panic(fmt.Errorf("not implemented: Depressions - depressions"))
}
