// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"learn-gqlgen/infra/datastore"
	"learn-gqlgen/infra/datastore/gorm"
)

// Injectors from wire.go:

func InitializeApp() App {
	db := datastore.NewMySqlDB()
	gormDBWrapper := gorm.NewGormDBWapper(db)
	app := NewApp(gormDBWrapper)
	return app
}
